plugins:
  ubiquity-os-marketplace/command-start-stop@demo:
    skipBotEvents: false
  ubiquity-os/command-demo@demo: null
  ubiquity-os-marketplace/command-wallet@demo: null
  ubiquity-os-marketplace/command-query@demo: null
  ubiquity-os-marketplace/text-conversation-rewards@v1.7.9:
    skipBotEvents: false
    with:
      incentives:
        collaboratorOnlyPaymentInvocation: false
        contentEvaluator:
          openAi:
            endpoint: "https://openrouter.ai/api/v1"
            model: "deepseek/deepseek-r1-0528:free"
        userExtractor: {}
        dataPurge: {}
        formattingEvaluator: {}
        payment: {}
        githubComment: {}
        reviewIncentivizer: {}
        simplificationIncentivizer: {}
        externalContent:
          llmImageModel:
            model: "meta-llama/llama-4-maverick:free"
          llmWebsiteModel:
            model: "deepseek/deepseek-r1-0528:free"
      payment:
        automaticTransferMode: false
      rewards:
        erc20RewardToken: "0x4F35e5C4D233f0cA201B3FFc006c29f6CefD1Fe7"
        evmPrivateEncrypted: "qNFc9GAJCIwB4IKO7nUaC8Vk3CvWeAe4_GuW6DbNwxu5O1958S5omdSkX9uuiUh52bEaAss-gMEaPQsSFLLSH1HqFO6jT7M9PPVCs_tiDPjBzfLHLU9fZxqePRGQApSD4imKvh6qO_67FR98dmdaiiKGtNJ0EE99FqHgAYbDF6jGx0jihw"
        evmNetworkId: 100
  ubiquity-os-marketplace/daemon-disqualifier@v1.0.3: null
  ubiquity-os-marketplace/text-vector-embeddings@v1.1.1:
    with:
      demoFlag: true
  ubiquity-os-marketplace/daemon-pricing@main:
    with:
      labels:
        time: *timeLabels
        priority: *priorityLabels
      basePriceMultiplier: 3
      shouldFundContributorClosedIssue: false
      globalConfigUpdate:
        excludeRepos: []
        
